version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "gantry"
    binary: gantry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

dockers_v2:
  - dockerfile: Dockerfile
    images:
      - "ghcr.io/ivanklee86/gantry"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64

homebrew_casks:
  - name: gantry
    homepage: "https://github.com/ivanklee86/gantry"
    description: "A CLI for Platform-izing devcontainers in microservices, widely distributed, or just complicated™ situations."
    directory: Casks
    repository:
      owner: ivanklee86
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_AUTH_TOKEN }}"
